export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'

export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST'

export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS'

export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE'

export const FETCH_PURCHASEDPRODUCTS_REQUEST = 'FETCH_PURCHASEDPRODUCTS_REQUEST'

export const FETCH_PURCHASEDPRODUCTS_SUCCESS = 'FETCH_PURCHASEDPRODUCTS_SUCCESS'

export const FETCH_PURCHASEDPRODUCTS_FAILURE = 'FETCH_PURCHASEDPRODUCTS_FAILURE'

export const ADD_BALANCE_REQUEST = 'ADD_BALANCE_REQUEST'

export const ADD_BALANCE_SUCCESS = 'ADD_BALANCE_SUCCESS'

export const ADD_BALANCE_FAILURE = 'ADD_BALANCE_FAILURE'

export const BUY_PRODUCT_REQUEST = 'BUY_PRODUCT_REQUEST'

export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS'

export const BUY_PRODUCT_FAILURE = 'BUY_PRODUCT_FAILURE'

export const DECREMENT_PRODUCT_QUANTITY_REQUEST = 'DECREMENT_PRODUCT_QUANTITY_REQUEST'

export const DECREMENT_PRODUCT_QUANTITY_SUCCESS = 'DECREMENT_PRODUCT_QUANTITY_SUCCESS'

export const DECREMENT_PRODUCT_QUANTITY_FAILURE = 'DECREMENT_PRODUCT_QUANTITY_FAILURE'
