export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'

export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST'

export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS'

export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE'

export const FETCH_PURCHASEDPRODUCTS_REQUEST = 'FETCH_PURCHASEDPRODUCTS_REQUEST'

export const FETCH_PURCHASEDPRODUCTS_SUCCESS = 'FETCH_PURCHASEDPRODUCTS_SUCCESS'

export const FETCH_PURCHASEDPRODUCTS_FAILURE = 'FETCH_PURCHASEDPRODUCTS_FAILURE'
